### ISSUE TITLE
Turn on Travis-CI

### ISSUE THREAD

**Issue by dblock** [JessRudder/JRHostsFile#3]
1. Go to https://travis-ci.org/profile/JessRudder
2. Find JRHostsFile
3. Flip the switch.

**Comment by JessRudder** [comment]
Travis was on - the link to the badge was broken.  The link had my username as "jessrudder" - it's apparently case sensitive.  I've updated to "JessRudder" and it's correctly showing now.

**Comment by dblock** [comment]
:+1:
